### ISSUE TITLE
Infistar shut down the menu

### ISSUE THREAD

**Issue by sercanatici** [noxsicarius/Custom-Actions-Menu#5]
So i have resently installed your script, but it isnt working for regular players. They get a sec to just see the action menu after scroll wheel and tap the action menu. I tested it without infistar, well it worked. i have wrote the ,'#USER:ActionMenu','#USER:ActionsMenu','#USER:VehicleMenu','#USER:FunMenu','#USER:MovementMenu','#USER:TransformAnimalMenu','#USER:DamiSpawn'

My looks like this:
[dayz_server.zip](https://github.com/noxsicarius/Custom-Actions-Menu/files/561466/dayz_server.zip)

Hope you can help me out.

**Comment by noxsicarius** [comment]
Post in the rpt file so I can see what's going on

**Comment by noxsicarius** [comment]
Post in the rpt file so I can see what's going on

**Comment by noxsicarius** [comment]
It looks like the infistar systems have changed and he may be disallowing all command menus. Depending on what the rpt files say you will have to enable command menus before it even attempts to let anything through again.

**Comment by sercanatici** [comment]
Thanks for the reply. Do you still need the rpt files. To fix this problem i had to change cMenu to false.

**Comment by noxsicarius** [comment]
That's what I thought. Looking through the files it seemed that the creator had made all menus disabled other than the ones built into the app. The wording was really weird on the files, but it seems like it was disallowing ALL menus and with that variable set to false it will now disallow all menus EXCEPT the ones that are listed as allowed in the section you modified for this tool.

**Comment by noxsicarius** [comment]
And no I do not.
