### ISSUE TITLE
Update to 1.0.6

### ISSUE THREAD

**Issue by sercanatici** [noxsicarius/Custom-Actions-Menu#6]
Would you be able to update it to the new epoch 1.0.6?
Cheers

**Comment by noxsicarius** [comment]
Have you tried using it on this version? I haven't checked to see if this works with that version or not. If not it will be fixed after the admin tools release. The tools are one of the most popular mods so they take priority.

**Comment by sercanatici** [comment]
I installed it on the epoch 106, some function worked but some others didnt.

**Comment by noxsicarius** [comment]
Can you list what did not work or whatever you can remember? It helps speed things up so I don't have to do extensive testing.

**Comment by sercanatici** [comment]
As i remember everything was working, just not the deploy. I didnt test much either, i was only going to use the deploy bike part

**Comment by noxsicarius** [comment]
Fixed in commits 095b9d8e99ffe5e8610016ad114e9f969d5b0ec8 and 9edb5a4fe60a160bf869b23a3ce57b4ca3d1aa19
